config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes, only: :new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DinnerMenu
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/recipes/_header.html.haml
.header
  .header_left
    = link_to "レシピアプリ", "#"
  .header_right
    %ul.header_right_list
      %li
        = link_to "ログイン", root_path
      %li
        = link_to "新規登録", new_recipe_path

app/views/recipes/index.html.haml
.menu
  = render "header"
  .menu_box
    .menu_box_search
      %input.menu_box_search_text{type: "text", placeholder: "料理"}
      %input.menu_box_search_submit{type: "submit",value: "検索"}
  .menu_titel
    %p 新規登録レシピ
  .menu_list
    .menu_list_name
      チャーハン
    .menu_list_name
      焼き飯
    .menu_list_name
      五目ご飯
    .menu_list_name
      天津飯
  .menu_content
    .menu_content_view
      = link_to "#" do
        .menu_content_view_image
    .menu_content_view
      = link_to "#" do
        .menu_content_view_image
    .menu_content_view
      = link_to "#" do
        .menu_content_view_image
    .menu_content_view
      = link_to "#" do
        .menu_content_view_image

app/views/recipes/new.html.haml
.recipe
  = render "header"
  .recipe_box
    .recipe_box_left
      = form_with model: @recipe do |f|
        .recipe_box_left_titel
          レシピ新規登録
        .recipe_box_left_name
          料理名
        .recipe_box_left_nameinput
          = f.text_field :name, placeholder: "例) たまご焼き"
        .recipe_box_left_image
          料理画像
        .recipe_box_left_imageinput
          = f.file_field :image
        .recipe_box_left_item
          材料
        .recipe_box_left_iteminput
          = f.text_field :item, placeholder: "例) たまご"
        .recipe_box_left_add
          ＋材料追加
    .recipe_box_center
      = form_with model: @recipe do |f|
        .recipe_box_center_menu
          作り方
        .recipe_box_center_input
          = f.text_area :item, placeholder: "例) フライパンに油をひきます。"
        .recipe_box_center_add
          ＋作り方追加
    .recipe_box_right
      = form_with model: @recipe do |f|
        .recipe_box_right_file_image
          画像
        .recipe_box_right_file_imageinput
          = f.file_field :image
        .recipe_box_right_file_comment
          コメント
        .recipe_box_right_file_commentinput
          = f.text_area :comment